FROM nginx:alpine

COPY web_application/index_hw1.html /usr/share/nginx/html/index.html
COPY web_application/css_style.css /usr/share/nginx/html/css_style.css
COPY web_application/script_hw.js /usr/share/nginx/html/script_hw.js

EXPOSE 80
